name: Build Alfred Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  # build:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions-rs/toolchain@v1
  #     with:
  #       toolchain: stable
  #       target: x86_64-apple-darwin
  #       override: true
  #   - uses: actions-rs/cargo@v1
  #     with:
  #       use-cross: true
  #       command: build
  #       args: --release --target "x86_64-apple-darwin"
  #   # cache the build assets so they dont recompile every time.
  #   - name: Cache Rust dependencies
  #     uses: actions/cache@v1.0.1
  #     with:
  #       path: target
  #       key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
  #       restore-keys: |
  #         ${{ runner.OS }}-build-
  #   - name: Copy executable
  #     run: mv ./target/x86_64-apple-darwin/release/kill_process ./alfred-workflow
  #   - name: Build Alfred Workflow
  #     id: alfred_builder
  #     uses: mperezi/build-alfred-workflow@v1
  #     with:
  #       workflow_dir: alfred-workflow
  #   - name: Create Release
  #     id: create_release
  #     uses: actions/create-release@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       tag_name: ${{ github.ref }}
  #       release_name: ${{ github.ref }}
  #       draft: false
  #       prerelease: false
  #   - name: Upload Alfred Workflow
  #     uses: actions/upload-release-asset@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       upload_url: ${{ steps.create_release.outputs.upload_url }}
  #       asset_path: ${{ steps.alfred_builder.outputs.workflow_file }}
  #       asset_name: ${{ steps.alfred_builder.outputs.workflow_file }}
  #       asset_content_type: application/zip

  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Rust dependencies
        uses: actions/cache@v1.0.1
        with:
          path: target
          key: ${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ hashFiles('**/Cargo.lock') }}
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          target: x86_64-apple-darwin
          default: true
          override: true
      - name: Build for mac
        run: ./build.sh
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Alfred Workflow
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kill-process.alfredworkflow
          asset_name: kill-process.alfredworkflow
          asset_content_type: application/zip
