name: Build Alfred Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Rust dependencies
        uses: actions/cache@v1.0.1
        with:
          path: target
          key: ${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ hashFiles('**/Cargo.lock') }}
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          target: x86_64-apple-darwin
          default: true
          override: true
      - name: Build for mac
        run: ./build.sh
      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-$GITHUB_RUN_NUMBER-$GITHUB_RUN_ATTEMPT"
          prerelease: true
          title: "Nightly"
          files: |
            kill-process.alfredworkflow
